### ISSUE TITLE
Optimize rendering pipeline for the non-happy-path

### ISSUE THREAD

**Issue by chkal** [eclipse-ee4j/krazo#104]
This issue aims to be some kind of umbrella discussion about a category of issues which is about the non-happy-path of an MVC request. So basically it is about what to do in case of exceptions and other scenarios.

Related issues:
  * CSRF validation vs. `@View` (issue #91 + PR #94)
  * Custom exception mappers problem (issue #34, PR #34)
  * Maybe others?

I'll try to summarize what my understanding of the underlying issue is. But I may be wrong with my following analysis. To be honest, I didn't find much time in the last weeks to dig into these issues. So please speak up if my statements don't make sense to you.

In a nutshell our rendering pipeline works like this (for the happy path):

  1. The controller is invoked and returns a view name (or `null` for `@View`)
  2. The `ViewResponseFilter` kicks in, checks the controller's return value (and `@View`) and replaces the response entity with a `Viewable` containing all the required information for rendering.
  3. The `ViewableWriter` then is called by the JAX-RS implementation to actually render the view.

This works fine on the happy path. Now if exceptions occur (like for a failed CSRF validation), things are getting more complicated. It looks like in this case step (2) is executed which leads to all sorts of problems:

  * An exception mapper may want to create a plain text response but the filter will try to render a corresponding view (see #34).
  * The filter will look for `@View` annotations if a mapper created a null-entity (see #91)
  * I'm pretty sure there are more issues...

So I'm wondering whether we can find a really simple solution for all of this. What if we just check in `ViewResponseFilter` if we are on the happy path (controller was executed successfully) do nothing otherwise. What does this mean? IMO all the problems mentioned above are gone. Exception mappers can do their work as they can without Krazo in the classpath. 

The only remaining question: what if the mapper wants to render a view? In this case he could simply use a `Viewable` for the entity in which case the request processing will continue as usual with step (3). For now this would be a Krazo-specific feature as `Viewable` is not part of the API anymore. Actually we removed it back then because the spec was very vague about many specific aspects. But I'm absolutely fine with adding it back to the spec for the next spec release.

@gtudan @erdlet Thoughts? As mentioned above, maybe I'm missing something obvious here.

**Comment by chkal** [comment]
BTW: I think that #94 is a real good basis for the fix I'm suggesting here.

**Comment by gtudan** [comment]
I like the idea, especially for the simplicity. 

As far as I understand, this would be the flip side of what @erdlet and I discussed in #34: our idea was to wrap the response in a custom class _if Krazo should not_ interpret the response as view. Here exception handlers would need to decorate their response as view _if_ they want it to get processed by a view engine.

My understanding was that an exception mapper always returns a view in the response. Surprisingly the spec doesn't say much about how exception handling should work, so we could do this without violating it. 

The downside is that we would not have custom exception pages in MVC (at least not without compile time Krazo dependencies) until we update the Spec/API.

**Comment by chkal** [comment]
> As far as I understand, this would be the flip side of what @erdlet and I discussed in #34: our idea was to wrap the response in a custom class _if Krazo should not_ interpret the response as view. Here exception handlers would need to decorate their response as view _if_ they want it to get processed by a view engine.

Yes, that's correct. As exception mappers typically don't know the difference between MVC and non-MVC requests, it would be weird if mappers need to add special handling to NOT get processed by the MVC implementation.

> My understanding was that an exception mapper always returns a view in the response. Surprisingly the spec doesn't say much about how exception handling should work, so we could do this without violating it.

Yes, I agree that the spec will need some more clarification regarding exception mappers.

> The downside is that we would not have custom exception pages in MVC (at least not without compile time Krazo dependencies) until we update the Spec/API.

Yes, that's definitely a downside. However, I don't think that this will be a huge problem. Especially because Krazo is the only implementation so far.

**Comment by erdlet** [comment]
I like this simple happy-path idea too, because we don't need complex logic for special cases as in #34 and the ExceptionMappers behave more "natural". 

I don't think I've other aspects to add to this discussion as the already mentioned.

So from my side a clear +1 to this suggestion

**Comment by chkal** [comment]
@erdlet @gtudan Thanks for your feedback.

I'm quite busy for the rest of the week. Especially because I'm working on the release setup. Maybe I'll find some time for a prototype over the weekend. But if you want to start with implementing a first draft, help is of course welcome. :-)

**Comment by chkal** [comment]
Just a small update. I created a prototype and it seems to work great. But I'm running into some weird test issue. For some reason my integration tests work fine in the IDE, but they fail when running on the command line. I'll provide more feedback tomorrow.

**Comment by chkal** [comment]
Closed via #106
