### ISSUE TITLE
Update old dependencies

### ISSUE THREAD

**Issue by erdlet** [eclipse-ee4j/krazo#115]
While checking one of our `pom.xml`s, I recognized a few (really) old dependencies we should update. Fortunately, most of them are test scoped or in our examples and won't affect the productive code.

| Module | Dependency | Current Version (Year) | New Version | Comment |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| core | easymock | 3.3.1 (2015) | 4.1 | [CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21350) (:heavy_check_mark:) done in #149 |
| core | weld-se-core | 2.4.8Final (2018) | 3.1.3.Final | [CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21351) (:heavy_check_mark:) removed in #149 |
| core | hibernate-validator-cdi | 5.4.1.Final (2017) | 6.1.0.Final | [CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21352) (:heavy_check_mark:) done in #149 |
| core | javax.el | 3.0.1-b08 (2015) | 3.0.1-b11 | I have no idea where I found version 4.1, so just upgrade to bugfix release 11 |
| ~examples~ | ~javaee-web-api~ | ~7.0 (2013)~ | ~8.0.1~ | done in  #116  |
| ~examples~ | ~htmlunit~ | ~2.15 (2015)~ | ~2.36~ | [CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21353)(:heavy_check_mark:) / done in #133 |
| ~ext~ | ~freemarker~ | ~2.3.28 (2018)~ | ~2.3.29~ | done in #117  |
| ~ext~ | ~handlebars~ | ~4.1.0 (2018)~ | ~4.1.2~ | done in #117 |
| ~ext~ | ~mustache~ | ~0.9.5 (2017)~ | ~0.9.6~ | done in #117 |
| ~ext~ | ~pebble~ | ~3.0.10 (2019)~ | ~3.1.1~ | done in #120 |
| ~ext~ | ~ST4~ | ~4.0.8 (2014)~ | ~4.2~ | [CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21354)(:heavy_check_mark:) / done in #137  |
| ~ext~ | ~Thymeleaf~ | ~3.0.10 (2018)~ | ~3.0.11~ | done in #117 |
| ~tck~ | ~javaee-web-api~ | ~7.0 (2013)~ | ~8.0.1~ | done in  #116 |
| ~testsuite~ | ~arquillian-bom~ | ~1.4.0 (2018)~ | ~1.5.0~ |  [CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21355)(:heavy_check_mark:) / done in #138|
| ~testsuite~ | ~arquillian-drone-bom~ | ~2.3.1 (2017)~  | ~2.5.1~ | [CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21356)(:heavy_check_mark:) / removed in favor of plain htmlunit |
| ~testsuite~ | ~graphene-webdriver~ | ~2.3.1 (2017)~ | ~2.3.2~ | ~needs to be updated in sync with `arquillian-drone-bom` because of Selenium version~ / removed in favor of plain htmlunit |
| ~testsuite~ | ~slf4j-simple~ | ~1.6.4 (2011)~ | ~1.7.30~ | [CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21357)(:heavy_check_mark:) / done in #138 |
| ~testsuite~ | ~htmlunit~ | ~2.32 (2018)~ | ~2.36.0~ | [CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21353)(:heavy_check_mark:) / done in #138  |

I think it makes sense to manage some of these dependencies in the parent pom, so we don't have version differences for the same artifact, e.g. like for the JEE Web API at the moment.

**Comment by chkal** [comment]
Thanks a lot! I'm basically +1 for this. But as we are currently in the process of preparing our first release, we should wait a bit with this and perform the update after that.

**Comment by erdlet** [comment]
> we should wait a bit with this and perform the update after that

+1 for this.

**Comment by chkal** [comment]
I already created a CQ for Pebble: http://dev.eclipse.org/ipzilla/show_bug.cgi?id=21167

BTW: The Eclipse Handbook also states:

> Project teams are not required to engage with the IP Team to review service releases for third party content, provided that the service release is based on a release that has either been license certified or approved by the IP Team. A service release is defined as a release that is backwards compatible and contains only bug fixes.

So updating to a new patch release should be fine without filing CQs. Maybe we should do this now. A few updates seem to be only patch release updates (like Handlebars and Thymeleaf)

**Comment by erdlet** [comment]
> So updating to a new patch release should be fine without filing CQs. Maybe we should do this now

Sounds like a plan. I'll have a look on this tomorrow.

**Comment by chkal** [comment]
The Pebble 3.1.1 CQ is approved. So if anyone has some time for providing a PR, feel free to do so. :-)

**Comment by erdlet** [comment]
I just created all CQ for dependencies where it is necessary.

**Comment by chkal** [comment]
Awesome! I guess it will take some days to get the approval because of the holidays.

**Comment by erdlet** [comment]
Ivar approved them already, but it seems that some of the bigger
repositories have different licenses which need additional checks by the IP
team (e.g. EasyMock). Let's see how long this takes.

Christian Kaltepoth <notifications@github.com> schrieb am Di., 31. Dez.
2019, 13:47:

**Comment by erdlet** [comment]
This whole Arquillian stuff in `testsuite` is driving me crazy. I can't upgrade htmlunit AND the Arquillian dependencies, as they rely on old selenium versions and drivers and these are incompatible to htmlunit:2.36.0.

It seems that we need to decide, if it makes more sense to update the Arquillian dependencies or htmlunit in this module.

**Comment by chkal** [comment]
Yeah, updating Arquillian can be a PITA. A few years ago it was impossible to use the latest Arquillian version together with the latest Shrinkwrap version. I spent many hours trying to solve this issue.

Why does Arquillian depend on HTMLUnit? I guess it is because of Drone?

TBH: I never understood why people use Drone. Isn't it easier to use webdriver/htmlunit directly? Or am I missing something (my knowledge about Drone is from ~2015).

**Comment by erdlet** [comment]
> I guess it is because of Drone?

You guess it right. Drone depends on an outdated `selenium-htmlunit` version (2.28). This version depends on some really old w3c dependency which was removed by `htmlunit` in one of the latest releases, but leads to `ClassNotFoundException`s now.

I don't use in in my integration tests because I like the htmlunit API more and it's easier IMO. So from my side we could remove this drone stuff and rewrite the tests to use htmlunit directly. This would have the advantage, that we don't have this dependency hell anymore and all tests will have a common form.

**Comment by chkal** [comment]
> I don't use in in my integration tests because I like the htmlunit API more and it's easier IMO. So from my side we could remove this drone stuff and rewrite the tests to use htmlunit directly. This would have the advantage, that we don't have this dependency hell anymore and all tests will have a common form.

+1

Basically we just do simple assertions on the received HTML content and no complex cross browser testing. So I guess using HTMLUnit directly is fine. Especially, because we already do it this way in the TCK:

https://github.com/mvc-spec/mvc-tck/blob/d7f29893a4df7421025c8ce8d31ce4a4990a3153/tests/src/main/java/org/mvcspec/tck/tests/viewengine/base/ViewEngineBaseTest.java#L63-L68

I'll create a corresponding issue.

**Comment by erdlet** [comment]
Updates are finally done.

**Comment by chkal** [comment]
Awesome! :beers:
