### ISSUE TITLE
Double format problems when using <input type="number">

### ISSUE THREAD

**Issue by erdlet** [eclipse-ee4j/krazo#118]
## Description
I recognized that the `NumberConverter` can't handle decimals from a number input field properly when using a non-english (or better: not-dot separated) locale.

Because the browser only sends dot-separated values to the server, the german-localed `NumberFormat` is not able to parse the value correct.

It would be great to find a solution for this, as the workaround, which is using a text input, is not the best solution from an semantic perspective (and UX perspective or accessibility perspective).

## Example
*Locale:* de-DE (via Accept-Language header)
*Input value:* 899,9 (HTML page & input is localed as german via MvcContext#getLocale)
*Request param:* "899.9"
*Output value:* 8999.0

## Reproduction
Simply take the current `DoubleConverterTest` and change the Locale in `ConversionTest` from `ENGLISH` to `GERMAN`.

## Workaround
Just use a text input field.

**Comment by erdlet** [comment]
@chkal @gtudan what is your opinion on this (I saw, that you two worked a lot on the converters and tests). 

I think it's not that critical that we need to fix this before the release, but in the future it would be good to have a working decimal number input field because of the reasons mentioned above (I forgot to mention, that a number input field is ways better for mobile phones than a normal text field).

**Comment by chkal** [comment]
Thanks for bringing this up.

I already ran into a similar issue a year ago in some other context:

Imagine a `<input type="number">` on a plain old HTML form:

* User 1
  * Uses a modern browser which supports HTML5 number inputs
  * The user enters `1,234` (German format)
  * The browser will submit: `1.234`
* User 2
  * Uses an older browser which doesn't support number inputs
  * The user enters `1,234` (German format)
  * The browser will fall back to standard `text` number inputs and submit: `1,234`

Now you have two outcomes. Either the result is `1234` or `1.234` depending on which locale you use and you cannot distinguish them.

:disappointed:

**Comment by erdlet** [comment]
Did you find a solution in this other context? Or was the solution the workaround the same I use now by using textboxes?

It seems to me, that this is more an HTML issue because the number inputs are not really internationalizable :thinking:

**Comment by gtudan** [comment]
Hi Tobias,

You are right, input type number has quiet a few known issues when it comes to internationalization. Take a look at the known issues tab on caniuse: https://caniuse.com/#feat=input-number
Depending on the browsers and locales you need to support you *might* improve things by setting a locale on the input or the page (lang=„de“). If that doesn’t help you probably have to fall back to a text input with a pattern as validator and/or JavaScript validation/ui-enhancements.

**Comment by erdlet** [comment]
Hi Gregor,

thanks for that detailed explanation and the link to the known issues. I wasn't aware of the tab in caniuse :) 

With this information I think this is nothing we can solve in Krazo. But maybe we can document this problem somewhere to avoid bug reports by other users?

**Comment by chkal** [comment]
> With this information I think this is nothing we can solve in Krazo.

Yeah, I guess this is really something that we cannot fix on our side. Unfortunately. However, I would still be interested to hear how other framework try to solve this issue.

> But maybe we can document this problem somewhere to avoid bug reports by other users?

Sure. Not sure where/how to do this. I guess we still need to decide if it is worth to create some kind of "Krazo documentation". So far the spec was in focus and 90% of all relevant information is available in the spec document. However, of course there are also Krazo-specific aspects which needs to be documented somewhere.

**Comment by gtudan** [comment]
> I would still be interested to hear how other framework try to solve this issue.

![javascript-javascript-everywhere](https://user-images.githubusercontent.com/419425/69899099-e0a6ba80-1361-11ea-917b-615e267f0ff9.jpg)

> Sure. Not sure where/how to do this. I guess we still need to decide if it is worth to create some kind of "Krazo documentation". So far the spec was in focus and 90% of all relevant information is available in the spec document. However, of course there are also Krazo-specific aspects which needs to be documented somewhere.

I remember we had a discussion about that on the mailing list some time ago, but lost track of it. In the last month we wrote quiet a bit of off-spec features, so I’d love to see a Krazo user guide!
Should we create an issue for that?

**Comment by erdlet** [comment]
I'd propose that we simply use the GitHub Wiki for Krazo specific
documentation.

I'll have a look on how other frameworks behave when using
internationalized number fields next week.

Gregor Tudan <notifications@github.com> schrieb am Sa., 30. Nov. 2019,
11:10:

**Comment by lefloh** [comment]
AFAIK the HTML spec differentiates between a "wire format" and a "presentation format". The wire format is standardised: e.g [`3.14` for floating points](https://www.w3.org/TR/2011/WD-html-markup-20110405/datatypes.html#common.data.float) and [`yyyy-mm-dd` for dates](https://www.w3.org/TR/2011/WD-html-markup-20110405/datatypes.html#form.data.date). The presentation format should be handled by the client. A date is a good example that the format can be quite different (other locale, graphical pickers or things like "next monday").
For non-supporting browsers I'd always try to enhance text fields via JavaScript.
If you implement your applications like this you should not use the browsers locale when parsing numbers.
If you also want to support JS-less clients you could work with fallback patterns when parsing.
Of course this does not cover all cases and might fail but I think there's no bullet proof solution here.

See also [this Stackoverflow post](https://stackoverflow.com/a/9519493/1353722).

**Comment by erdlet** [comment]
Thanks a lot for this additional information, this format / internationalization topic is really interesting and confusing at the same time.

> If you also want to support JS-less clients you could work with fallback patterns when parsing.
> Of course this does not cover all cases and might fail but I think there's no bullet proof solution 
> here.

Hmm think you are absolutely right here. It's a little bit sad, that this number input has these problems because it helps a lot, especially on mobile devices.

I'll try a few things with this new information and maybe I find a solution which doesn't need a lot of JavaScript.

**Comment by erdlet** [comment]
Hi all,
I tried a few things and found something which seems weird to me:

When I set the language of an number input with the `lang` tag in `<html>` to `de` and post its value to a controller whose `@FormParam` is of type `double` and _not_ annotated with `@MvcBinding`, the german input of `1000,50` is resolved correctly as `1000.5`, because the browser converts it into the correct wire format. 
But when I annotate the `@FormParam` additionally with `@MvcBinding`, our `DoubleConverter` kicks in and produces a wrong conversion, because it wants to format the double value from the browser with the browser's `Locale` format.

I think this behaviour is the real problem which occured in my application, because the browser behaves correctly.

In my opinion, this is a bug on Krazo side, because we try to parse an already correct value to something "invalid". Maybe a solution is could be a check, if the `String` we receive in the `DoubleConverter` has already the wire format and only parse with the browser-locale if it doesn't have it (this would be the case e.g. for text-inputs which send something like `1000,0` for the german locale).

What is your opinion on this? 

I'll push and link my example project where I tested this, so in case I did something wrong you can tell me ;)

**Comment by chkal** [comment]
> But when I annotate the `@FormParam` additionally with `@MvcBinding`, our `DoubleConverter` kicks in and produces a wrong conversion, because it wants to format the double value from the browser with the browser's `Locale` format.

Yes, in a sense this is expected, because we parse numbers according the locale produced by the LocaleResolver. Of course this only make sense if values are submitted in the localized number format and NOT in the wire format.

> Maybe a solution is could be a check, if the `String` we receive in the `DoubleConverter` has already the wire format and only parse with the browser-locale if it doesn't have it (this would be the case e.g. for text-inputs which send something like `1000,0` for the german locale).

Unfortunately I think that's not possible. At least if you also try to support the grouping separator. Imagine that the browser sends `1.234` and the `LocaleResolver` resolved `de-DE`. What would be the result of binding the value to a double field?

  1. `1234` (assuming that the `.` is the grouping character for `de-DE`)
  2. `1.234` (assuming that the `.` is the decimal separator for `en-US`)

As mentioned before, I never found a solution for this problem but I would really be interested to see how for example Spring Boot or good old Struts handles locale-aware data binding.

**Comment by erdlet** [comment]
> As mentioned before, I never found a solution for this problem but I would really be interested to see how for example Spring Boot or good old Struts handles locale-aware data binding.

I just copied my example to a Spring Boot application and tested the behavior of either number and text input fields with different locales. Spring MVC doesn't use any locale when parsing floating point numbers (deep inside, it uses its `NumberUtils#parseNumber`). Instead it throws a HTTP `400` in case a non-wire-formatted value is send in the request. Nevertheless, it would be possible to write a custom `ConversionService` to perform such parsing. I think, that this decision is made because of the reasons Florian mentioned related to wire and presentation format.

I didn't had a look on Struts until now, but I guess it will work the same way Spring does.

**Comment by erdlet** [comment]
OK, I'm a little bit surprised. Struts seems to handle the floating point values like we do. The `com.opensymphony.xwork2.conversion.impl.NumberConverter` looks also for the current action locale and formats the input depending on it. This leads to the same effect I recognized in Krazo.

So for me it seems, that there is not "the correct way". Spring is oriented on the standardized float format, whereas Struts and Krazo try to resolve these locale specific, leading to the current issue in case the new number field is used.

> As mentioned before, I never found a solution for this problem...
After this analysis I don't see a "one size fits all" solution, but I think it would be a good idea to support both ways of floating point number parsing, where one is locale aware and one simply expects the wire format. This could be achieved by a config entry, so anyone can select its prefered style for creating inputs.

**Comment by lefloh** [comment]
Thanks for your analysis @erdlet!
I agree that there's no right or wrong solution here. Important is in my eyes that the default behaviour is well documented and easy to change for the developer.

**Comment by gtudan** [comment]
Maybe we should let the developers choose if Krazo applies any locale by making it configurable?

**Comment by lefloh** [comment]
Just for the records: We could also allow to register custom instances of `MvcConverter`. But I guess most developers would be happy with a simple configuration option.

**Comment by erdlet** [comment]
> But I guess most developers would be happy with a simple configuration
option.

+1 for this. I think most developers want either to use the "old way" with
text fields or HTML5 number inputs. I guess when we provide converters for
those ways, the most common use cases are covered.

Florian Hirsch <notifications@github.com> schrieb am Di., 10. Dez. 2019,
08:36:

**Comment by chkal** [comment]
> We could also allow to register custom instances of `MvcConverter`. But I guess most developers would be happy with a simple configuration option.

+1 for this. This was also one of the features I had in mind for MVC 1.1 :-)

> Maybe we should let the developers choose if Krazo applies any locale by making it configurable?

We could provide an additional annotation like `@ForceLocale(Locale.ENGLISH)` or something like that.

**Comment by erdlet** [comment]
> We could also allow to register custom instances of MvcConverter. But I guess most developers would be happy with a simple configuration option.

>> +1 for this. This was also one of the features I had in mind for MVC 1.1 :-)

That might be the most powerful solution, so we can provide e.g. two converters for the most common cases and users can apply special converters also.

> We could provide an additional annotation like @ForceLocale(Locale.ENGLISH) or something like that.

You thought about an additional annotation to the custom converter registration mentioned above or to the current solution?

**Comment by chkal** [comment]
> That might be the most powerful solution, so we can provide e.g. two converters for the most common cases and users can apply special converters also.

Correct. However, one downside is that JAX-RS already provides a converter mechanism (`ParamConverter`) and it may be weird to have a "second layer" on top if it. That was the most important reason for me to not target this feature for MVC 1.0.

> > We could provide an additional annotation like @ForceLocale(Locale.ENGLISH) or something like that.
> 
> You thought about an additional annotation to the custom converter registration mentioned above or to the current solution?

I'm not completely sure what the best way is. My first idea was to have something like `@ForceLocale(Locale.ENGLISH)` or `@ForceWireFormat` which basically alters the behavior of the existing converters to use `Locale.ENGLISH` instead of the request locale for parsing the values.

An alternative would be to provide a more generic solution which allows you to choose a converter for each binding by using something like `@Convert(with=MyCustomConverter.class)`.

**Comment by erdlet** [comment]
> Correct. However, one downside is that JAX-RS already provides a converter mechanism (ParamConverter) and it may be weird to have a "second layer" on top if it. That was the most important reason for me to not target this feature for MVC 1.0.

Maybe we don't need a whole layer above. I thought about extending our `ConverterRegistry` to allow adding custom converters which may have some specific logic in their `supports` method or simply a different implementation of `convert`. This won't be much effort and may be enough. As we already use a list to store them, we even can handle the priorities of converters this way.

> I'm not completely sure what the best way is. My first idea was to have something like `@ForceLocale(Locale.ENGLISH)` or `@ForceWireFormat` which basically alters the behavior of the existing converters to use `Locale.ENGLISH` instead of the request locale for parsing the values. An alternative would be to provide a more generic solution which allows you to choose a converter for each binding by using something like `@Convert(with=MyCustomConverter.class)`.

Hmmm I'm afraid this could lead to a annotation hell, especially when someone wants to use e.g. the wire format in every case a double appears. But in general I think this is an improvement anyway for special cases, so why no think about providing both ways (adding custom converters and those annotations)?

**Comment by chkal** [comment]
@erdlet Sorry for my delayed reply.

> Maybe we don't need a whole layer above. 

I agree on this one. Especially because I'm not completely sure whether having a converter API on the spec level makes sense, we should definitely experiment with this idea in the implementation first.

> I thought about extending our `ConverterRegistry` to allow adding custom converters which may have some specific logic in their `supports` method or simply a different implementation of `convert`. This won't be much effort and may be enough. As we already use a list to store them, we even can handle the priorities of converters this way.

+1 for this. This is also what I had in mind when I first created the `ConverterRegistry`. Maybe now is the time to enhance this converter API... :-)

> Hmmm I'm afraid this could lead to a annotation hell, especially when someone wants to use e.g. the wire format in every case a double appears. But in general I think this is an improvement anyway for special cases, so why no think about providing both ways (adding custom converters and those annotations)?

Yes, this would definitely be annotation hell. 

**IF** we decide to move this feature into the spec, we could add more attributes to `@MvcBinding`. But as mentioned above, I'm not completely sure if this should go into the spec.

So for now my vote goes for creating a way for developers to provide custom converters. Maybe this is enough.

**Comment by erdlet** [comment]
> So for now my vote goes for creating a way for developers to provide
custom converters. Maybe this is enough.

I'll have a look on this. Maybe I've some time for a prototype this weekend.


Christian Kaltepoth <notifications@github.com> schrieb am Fr., 13. Dez.
2019, 17:24:

**Comment by chkal** [comment]
> I'll have a look on this. Maybe I've some time for a prototype this weekend.

Awesome! :beers:

**Comment by erdlet** [comment]
This problem should be resolved with the `ConverterRegistry` extension. I'll close the issue.
