### ISSUE TITLE
Discuss structure of documentation

### ISSUE THREAD

**Issue by chkal** [eclipse-ee4j/krazo#122]
We mentioned that we need some kind of documentation multiple times. I guess we should start to discuss how to create this documentation now.

I guess we have the following options:

  1. Add a `docs` folder to the repo and start to write some AsciiDoc documentation. We could automatically publish this to the website and it is even versioned together with Krazo.
  2. We manage the documentation in the GitHub wiki.
  3. We create the documentation directly in the website repository by adding AsciiDoc files.

I personally like option (1). Especially because it allows us to use pull requests for editing the documentation and because it is automatically versioned.

Option (2) won't allow us to work with a pull request like process and option (3) makes versioning really hard (this becomes important as soon as we add/remove features).

Any other thoughts?

**Comment by erdlet** [comment]
I know I proposed the GitHub Wiki in the other issue, but after you mentioned the idea of AsciiDoc I'd really prefer this now (didn't thought of it the last time) :+1: 

I think that's the most easy solution, we're not depending on some proprietary wiki technology and the documentation is besides the code at any time.

**Comment by lefloh** [comment]
+1 for (1)

Tobias Erdle <notifications@github.com> schrieb am Fr., 6. Dez. 2019, 09:03:

**Comment by gtudan** [comment]
+1 for option one. Easier PR and versioning the documentation together with Krazo are good arguments for it.

I personally don‘t like the github wikis, as I haven‘t seen a a lot of good ones. They are quiet hard to structure and lack and export feature. It would also be hard for others to contribute to it without PR or permissions.

Option 3 is okay, but I prefer having the documentation in the same repo as the source code. But this is more of a personal preference 🙂

**Comment by chkal** [comment]
Looks like we have an agreement. I'll prepare the base structure and create a pull request soon.

**Comment by Daniel-Dos** [comment]
Hello,

I like of option (1) :  )

**Comment by chkal** [comment]
I just created #128 which provides the new Maven module which we can use for the documentation. I guess the next step would be to discuss a very rough structure, so we can create the corresponding chapters and sections.

**Comment by erdlet** [comment]
> to discuss a very rough structure, so we can create the corresponding chapters and sections.

These are a few ideas for topics from my side (assuming, that we write doc for users and devs):

## For users
- **Installation guides** (migrate them from MVC Spec website and link only to Krazo doc there)
- **SPIs and how to use them**
- **Configuration of the view-engine extensions** (e.g. how to configure Thymeleaf in our extension)

## For devs
- **General information** (like this whole ECA stuff, issue tracking, etc.)
- **Code Style & Conventions**
- **Known issues and restrictions** (e.g. because of / in JAX-RS)

**Comment by chkal** [comment]
A few thoughts from my side. I'm not sure if the "for devs" part should have a priority or now, but we could add it as a section to the documentation later on.

What about a structure like this:

* Introduction
* Quickstart (with introduction explaining the three main modules)
  * Base setup
    * Java EE 8 / Jakarta EE
    * Java SE (Tomcat/Jetty)
  * Creating a first controller
* Configuration
  * (Maybe just a general intro to how JAX-RS properties work + a list of all parameters)
* Additional View Engines
  * Thymeleaf
  * Freemarker
  * Velocity
  * ...
* Advanced features
  * (Change HTTP method via form parameter)
  * ...
* Extension points
  * (one section per SPI)
* Krazo development
  * General Info
  * Code style
  * Known issues

**Comment by erdlet** [comment]
I like this structure and think that covers everything we need as documentation.

**Comment by Daniel-Dos** [comment]
Hi,

I liked the structure, it's well formulated.

**Comment by chkal** [comment]
I created a pull request for the basic structure: #130

**Comment by erdlet** [comment]
As we already mergend #130 I'll close this issue.
