### ISSUE TITLE
Update TomEE and Arquillian adapter

### ISSUE THREAD

**Issue by erdlet** [eclipse-ee4j/krazo#124]
We're currently running on the milestone version of TomEE. We should upgrade the server as well as the Arquillian adapter from `8.0.0-M3` to `8.0.0`.

@chkal Do we need a CQ for that?

**Comment by chkal** [comment]
+1 for updating our dependency. But I guess we should create corresponding CQs for them. These are `workswith` dependencies, so it shouldn't take very long.

**Comment by erdlet** [comment]
OK, I'll create a CQ for the adapter. This way I can try the wiki introduction to this process. The TomEE should be only the Docker container, so this should be out of scope for a CQ.

**Comment by chkal** [comment]
> OK, I'll create a CQ for the adapter.

Great! :-)

> The TomEE should be only the Docker container, so this should be out of scope for a CQ.

Yes, AFAIK we didn't create CQs for the docker containers yet. And I don't think that it is required.

**Comment by erdlet** [comment]
Just recognized that the dependency is also scoped wrong. It should be scoped as `test`. Just a small hint for the person fixing this :)

**Comment by erdlet** [comment]
[CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21317) is created

**Comment by chkal** [comment]
Looks like it is already resolved! Great! :-)

**Comment by erdlet** [comment]
It seems that the TomEE people didn't publish a 8.0.0 Docker image yet... The Dockerfiles are updated in their master, but not available in Dockerhub. Also, it's not possible to file an issue, because they deactivated their GitHub issues but link to it in their README...

**Comment by chkal** [comment]
Too bad. :disappointed: Looks like we have to wait some time to do this update.

**Comment by erdlet** [comment]
I opened a thread on the TomEE users mailing list and asked, when the containers are going to be released. Found some discussion about the Docker images in their dev mailing list, but had no idea what they were talking about. Maybe they explain it on the new thread.

**Comment by chkal** [comment]
Awesome. Thanks.

**Comment by erdlet** [comment]
I wrote another mail to the mailing list, because the first one was maybe overseen because of christmas and new year.

**Comment by erdlet** [comment]
Done in #160
