### ISSUE TITLE
OpenLiberty: CXF ignores @MvcBinding for bean validation

### ISSUE THREAD

**Issue by erdlet** [eclipse-ee4j/krazo#144]
I recognized on CXF that the `@MvcBinding` annotation seems to be ignored when using it for parameter validation. On a method like this
```
@POST
    @UriRef("create-todo")
    @CsrfProtected
    public String createTodo(@NotEmpty @MvcBinding @FormParam("title") String title,
                             @NotEmpty @MvcBinding @FormParam("content") String content) 
```
the HTTP response has just HTTP status 400 and is returning an empty screen. Running the same code in a Jersey or RestEasy environment results in the expected filled binding result.

**Comment by chkal** [comment]
Thanks. Yes, IIRC we have many failing TCK test on CXF which are related to binding. Unfortunately the binding related code in Krazo is quite complex and uses some "dirty tricks" to disable the built-in bean validation mechanism. I guess this needs some more work to get it right.

**Comment by erdlet** [comment]
As we drop the CXF support from Krazo, this issue is obsolete.
