### ISSUE TITLE
@CsrfProtected does not work with Beanparam

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/krazo#145]
I created a form bean like this.

```java
@RequestScoped
public class TaskForm implements Serializable {

    private static final long serialVersionUID = 1L;

    @NotBlank
    @FormParam("name")
    @MvcBinding
    private String name;

    @NotBlank
    @Size(min = 10, max = 2000)
    @FormParam("description")
    @MvcBinding
    private String description;

//getters and setters
}
```

And set csrf token  in view template

```xhtml
<input type="hidden" name="${mvc.csrf.name}"
                           value="${mvc.csrf.token}"/>
```

And add `@CsrfProtected` on a controller method.

```java
    @POST
    //@CsrfProtected
    //@ValidateOnExecution(type = ExecutableType.NONE)
    public Response save(@Valid @BeanParam TaskForm form) {
}
```

When running the application and submit the form, get 403 error in the web pages and the Payara console shows the following info.

```bash
  A servlet request to the URI http://localhost:8080/jakartaee-mvc-sample/mvc/tasks/new contains form parameters in the request body but the request body has been consumed by the servlet or a servlet filter accessing the request parameters. Only resource methods using @FormParam will work as expected. Resource methods consuming the request body by other means will not work as expected.|#]
```

I also tried to add the csrf to [other simple controller methods which only have `@FormParam` parameters](https://github.com/hantsy/jakartaee-mvc-sample/blob/master/src/main/java/com/example/web/TaskController.java#L157-L172), still does not work.

**Comment by hantsy** [comment]
I have created another simple sample to reproduce it in my project.

```java
@Path("greeting")
@Controller
@RequestScoped
public class GreetingController {

    @Inject
    BindingResult bindingResult;

    @Inject
    Models models;

    @Inject
    AlertMessage flashMessage;

    @Inject
    Logger log;

    @GET
    public String get() {
        return "greeting.xhtml";
    }

    @POST
   // @CsrfProtected
    @UriRef("greeting-post")
    public String post(
            @FormParam("greeting")
            @MvcBinding
            @NotBlank String greeting) {
        if (bindingResult.isFailed()) {
            AlertMessage alert = AlertMessage.danger("Validation voilations!");
            bindingResult.getAllErrors()
                    .stream()
                    .forEach((ParamError t) -> {
                        alert.addError(t.getParamName(), "", t.getMessage());
                    });
            models.put("errors", alert);
            log.info("mvc binding failed.");
            return "greeting.xhtml";
        }

        log.info("redirect to greeting page.");
        flashMessage.notify(AlertMessage.Type.success, "Message:" + greeting);
        return "redirect:greeting";
    }

}

```

And the page template.

```xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                template="/WEB-INF/layout/template.xhtml">
    <ui:define name="pageTitle">Say hello to MVC</ui:define>
    <ui:define name="content">
        <div class="row">
            <div class="col-md-12">
                <form id="form" name="form" role="form" class="form" action="#{mvc.uri('greeting-post')}" method="post">
                    <input type="hidden" name="${mvc.csrf.name}"
                           value="${mvc.csrf.token}"/>
                    <div
                        class="form-group">
                        <label class="control-label" for="greeting">Message:</label>
                        <input id="greeting" name="greeting" type="text" class="form-control"/>
                        <div class="help-block">
                        </div>
                    </div>

                    <div class="form-group">
                        <button id="submitTask" type="submit" class="btn btn-lg btn-primary">Send Greeting</button>
                    </div>
                </form>
            </div>
        </div>
    </ui:define>
</ui:composition>

```

**Comment by chkal** [comment]
Thanks a lot for reporting this. That's really weird. Not sure what is causing this. We have coverage for this aspect in the TCK and the TCK passes on Glassfish. However, we currently don't run the TCK against Payara. I'll try to find some time to dig into this issue in the next days.

**Comment by hantsy** [comment]
@chkal  Check my [sample here](https://github.com/hantsy/jakartaee-mvc-sample/), I am not sure if there are other configurations in my codes could cause this issue.

**Comment by chkal** [comment]
Thanks. Having a sample app to reproduce this is definitely helpful.

BTW: Did you test any other containers? Especially Glassfish or Wildfly?

**Comment by erdlet** [comment]
I just had a short look into this example and I recognized, that you are missing 
```
  @Override
    public Map<String, Object> getProperties() {
        return Map.of(Csrf.CSRF_PROTECTION, CsrfOptions.IMPLICIT);
    }
```
in your JAX-RS application. This way, your example code should work.

**Comment by hantsy** [comment]
@erdlet If I added the `@CsrfProtected` on the method, it will raise 403 on the page, and show the above error message(no exception stack there) in the application server console, so I commented it out temporarily in my codes.

**Comment by hantsy** [comment]
I have read the doc of `CsrfOptions`, by default, it is `EXPLICIT`, so we have to add a `@CsrfProtected` annotation on the controller method to verify the CSRF token, right?

**Comment by erdlet** [comment]
@hantsy thanks for that explanation.
Do you have any interceptors disrupting the request processing?

I'll try your example this evening and give you feedback. On which Payara version and Java version are you running this example?

>  by default, it is EXPLICIT, so we have to add a @CsrfProtected annotation on the controller method to verify the CSRF token, right?

That's correct, I was just irritated by the commented out annotation.

**Comment by hantsy** [comment]
Oh, I have used a [`HiddenHttpMethodFilter`](https://github.com/hantsy/jakartaee-mvc-sample/blob/master/src/main/java/com/example/web/HiddenHttpMethodFilter.java)(copied from Spring MVC) to convert `_ method`(PUT, DELETE) to controller `@PUT`, `@DELETE` methods.

**Comment by hantsy** [comment]
1. Payara 5.193
2. Java 8.

```bash
>java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)
```

**Comment by erdlet** [comment]
> Oh, I have used a HiddenHttpMethodFilter(copied from Spring MVC) to map the _ method form params(PUT, DELETE) to the controller's @PUT, @DELETE methods.

Don't know if this may be a problem, but generally you don't need a custom filter anymore as Krazo provides is own implementation :)

Thanks for the infrastructure information, I'll check this later ;)

**Comment by erdlet** [comment]
Nevertheless, can you please try to use the Krazo filter instead of your own? You just need to remove your implementation as the Krazo filter "listens" on the same hidden input as Spring's filter.

**Comment by erdlet** [comment]
I think this `String paramValue = request.getParameter(this.methodParam);` is the problem, as this method consumes the request body as far as I remember.

Krazo has its own [provider](https://github.com/eclipse-ee4j/krazo/blob/master/core/src/main/java/org/eclipse/krazo/security/DefaultFormEntityProvider.java) for getting a forms content because of an similar issue regarding the request body when handling forms.

**Comment by hantsy** [comment]
Got it, there is [an impl in Krazo](https://github.com/eclipse-ee4j/krazo/blob/master/core/src/main/java/org/eclipse/krazo/forms/HiddenMethodFilter.java).

**Comment by hantsy** [comment]
@erdlet  @hantsy Thanks for your help, I think this issue should be closed now.
