### ISSUE TITLE
Add a RedirectModels 

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/krazo#146]
There is a `Models` to serve the data rendering in the view template.  But for redirecting to a new view and show the data, currently, only a `@RedirectScoped` bean can do the work, if possible to add a `RedirectModels`(similar `Models`) to transfer the data to a redirected view. Or provide a general-purpose `ModelAndView` like Spring MVC.

**Comment by chkal** [comment]
To be honest, my impression is that the redirect-scope will be rarely useful. Of course, you need it for storing error/success messages when implementing the PRG-pattern. Or do you see other use cases?

Maybe this issue should be filed against the spec instead?

**Comment by hantsy** [comment]
Yes, just need a flush message(in other frameworks) for displaying messages/errors after the page is redirected to a new page.

Spring provides `@RedirectAttributes` and `ModelAndView` that work for this case. Maybe the spec itself should be improved.

Just need a simple approach to set data in redirect scope instead of creating a standalone `@RedirectScoped` bean.

**Comment by erdlet** [comment]
> if possible to add a RedirectModels (similar Models)

I think this would be a more user friendly approach than the `@RedirectScope`, because, as @chkal mentioned, the most common use case is storing success or error messages or other indicators.

> Maybe this issue should be filed against the spec instead?
:+1:

**Comment by erdlet** [comment]
Hi @hantsy,
I'd close this issue here to keep track of the Krazo related stuff. Please propose this issue in the [specification's issue tracker](https://github.com/mvc-spec/mvc-spec/issues), so it can be discussed there. I think this would be a good improvement of the spec.

Thanks again for sharing this idea!
