### ISSUE TITLE
Bean Validation does not work when @CsrfProtected is set  

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/krazo#148]
I have tried to deploy my [sample application](https://github.com/hantsy/jakartaee-mvc-sample) into the latest wildfly. 

* Wildfly 19.0.0.Beta1
* AdoptOpenJDK 8
* Win 10

```bash
mvn clean package wildfly:run -Pwildfly
```
But I found the form data validation did not work, I am  not sure it is relevant to csrf.

Try to add a Task, leave all fields are empty, and save it, all data will be saved.  

```java
@RequestScoped
public class TaskForm implements Serializable {

    private static final long serialVersionUID = 1L;

    @FormParam("id")
    private Long id;

    @NotBlank
    @FormParam("name")
    @MvcBinding
    private String name;

    @NotBlank
    @Size(min = 10, max = 2000)
    @FormParam("description")
    @MvcBinding
    private String description;
```

**Comment by chkal** [comment]
Thanks for reporting. The reproducer will definitely be helpful..

**Comment by hantsy** [comment]
For the simple binding, it seems it works, @chkal .

```java
    @POST
    @CsrfProtected
    public String post(
            @FormParam("greeting")
            @MvcBinding
            @NotBlank String greeting) {
```

**Comment by erdlet** [comment]
Hi @hantsy ,

I reproduced this case and found the problem:
```
@RequestScoped
public class TaskForm implements Serializable
```
When you remove the scope annotation, everything works. I assume `@BeanParam` is simply not designed to work with CDI beans, because the JavaDoc of the annotation states
`The runtime will instantiate the object and inject all it's fields and properties...` and there is no word or example of using CDI beans for this.

**Comment by hantsy** [comment]
Yes, just verify, after removing `@RequestScoped`, it works.

**Comment by chkal** [comment]
I agree with @erdlet. If you use `@BeanParam` on a method argument or controller class field, JAX-RS and not CDI will create instances of this class. So using `@RequestScoped` is definitely not required and won't work.

I'll close this for now. Feel free to reopen if you have further questions or doubts.
