### ISSUE TITLE
Support custom MvcConverters

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/krazo#150]
Currently, krazo 1.0 uses a `ConverterRegistry` to add a list of `MvcConverter` in a hard way.

For example, I want to convert a *yyyy-MM-dd* string to `LocalDate`. I found there is no way to create a custom `MvcConverter` CDI bean to make it available in krazo.

**Comment by erdlet** [comment]
Hi @hantsy,

thanks for the idea. We implemented this a few weeks ago for version 1.1.0. Please have a look into #123 and #141 

I don't know if there is already a milestone artifact containing the newest improvements, but maybe @chkal can create one the next days?

**Comment by erdlet** [comment]
@hantsy is this issue answered? If yes, I'd close it :)

**Comment by hantsy** [comment]
Thanks.

**Comment by chkal** [comment]
> I don't know if there is already a milestone artifact containing the newest improvements, but maybe @chkal can create one the next days?

Great idea. I'm not completely sure if we are allowed to do this now or if we need approval for the release plan first. I'll check this and start a discussion about the milestone planning on the list in the next days.
