### ISSUE TITLE
Add documentation around running tests

### ISSUE THREAD

**Issue by jcputney** [eclipse-ee4j/krazo#188]
Per comment on #187

...it would be nice to get some documentation around how to run the individual tests. I could probably sit down and figure out what profiles to run, but it would be helpful to have a quick example in the README.

_Originally posted by @jcputney in https://github.com/eclipse-ee4j/krazo/pull/187_

**Comment by erdlet** [comment]
Hi @jcputney,

Is the created documentation OK, or are there any questions left on running the tests? :)

In case there is no more information necessary, I'd close this issue to keep the issue list clean.

**Comment by erdlet** [comment]
As there is no further feedback, I'll close the issue for now.
