### ISSUE TITLE
ScopeId URL param exposes application design

### ISSUE THREAD

**Issue by jcputney** [eclipse-ee4j/krazo#197]
Is there a way to use something other than `org.eclipse.krazo.redirect.ScopeId` in the URL when redirecting? 

From a security standpoint, I may not necessarily want users to know that my application is using MVC/Krazo for its UI layer.

Update: Being able to override `RedirectScopeManager.PREFIX` would be great!

**Comment by chkal** [comment]
I like the idea of providing a configuration parameter to customize the name of the query parameter! We should definitely provide this as part of the next release.

**Comment by jcputney** [comment]
I created pull request #198 to provide this configuration item.

**Comment by chkal** [comment]
Fixed via #198
