### ISSUE TITLE
Thymeleaf view engine does not set content type

### ISSUE THREAD

**Issue by nikolaj-a** [eclipse-ee4j/krazo#200]
Pretty much what it says in the title. The `ThymeleafViewEngine` does not seem to properly set the response `Content-Type` header, which can sometimes cause problems.

I took a closer look at some of the other view engine implementations, and they all seem to call `ViewEngineBase#resolveCharsetAndSetContentType(ViewEngineContext)`. But they are also using a different mechanism for determining the output stream, so it might not necessarily be relevant.

This does seem to work, but I'm not sure if there are any hidden pitfalls with this approach as I'm not really familiar with the Krazo code at all:
```java
Charset charset = resolveCharsetAndSetContentType(context);
try {
    response.setHeader(HttpHeaders.CONTENT_TYPE, "text/html");
    this.engine.process(this.resolveView(context), ctx, new OutputStreamWriter(context.getOutputStream(), charset));
    response.flushBuffer();
} finally {
    ctx.close();
}
```
Upon further investigation it seems that none of the headers from the context are transferred to the response. So maybe it's more of a general issue than just the content type?

I'm not sure if this is the correct place for reporting issues about the Krazo extras, so please let me know if it isn't.

**Comment by chkal** [comment]
Hi! Thanks a lot for reporting this. This the correct place for reporting such issues, also for the "extras".

Just to double-check that I understood this correctly. Adding the `resolveCharsetAndSetContentType` call fixes this issue? I'm just asking because you also mentioned, that headers from the context aren't written to the response.

It maybe also worth trying the latest snapshots, because we reworked how Krazo handles content type resolution a few weeks ago.

https://www.mvc-spec.org/krazo/docs/install-snapshots.html

**Comment by nikolaj-a** [comment]
No, `resolveCharsetAndSetContentType` by itself is not enough (that was my first try 🙂). The `response.setHeader` is also required. I'm not too sure about that OutputStreamWriter. It might be needed to change the charset.

**Comment by nikolaj-a** [comment]
I tested out the snapshot version and that seems to work correctly - at least for the `Content-Type` header 👍 It does seem to omit the CSRF-related header that I was also expecting. Maybe I'm just misunderstanding how it's supposed to work, since I'm not really using the form submit stuff.

Any estimated release date?

**Comment by chkal** [comment]
> It does seem to omit the CSRF-related header that I was also expecting. Maybe I'm just misunderstanding how it's supposed to work, since I'm not really using the form submit stuff.

Could you elaborate on this? Which header do you mean?

> Any estimated release date?

Actually the release is overdue. But we are now in the process of releasing the first version of the MVC spec under the Jakarta EE umbrella. So this may take a bit of time to get this done.

**Comment by nikolaj-a** [comment]
I was expecting some CSRF token to be present as a header. I can't remember the name, but it was `X-CSRF-`-_something_. I still think this is more of a general issue that the response headers from the `ViewEngineContext` are pretty much ignored.

**Comment by chkal** [comment]
Ok. Could you perhaps create a new issue for this? Thanks a lot!

**Comment by nikolaj-a** [comment]
Yes, I certainly can 🙂 Maybe this one should be closed as resolved? Since the content type is actually working in the snapshot version.
