### ISSUE TITLE
Thymeleaf: Standard Dialect not working as expected

### ISSUE THREAD

**Issue by thomas-mc-work** [eclipse-ee4j/krazo#203]
Using the Standard Dialect doesn't create the expected results in my simple demo application:

    <!DOCTYPE html>
    <html xmlns="http://www.w3.org/1999/xhtml" xmlns:th="http://www.thymeleaf.org">
        <body>
            <form>
                <input type="text" name="userName" value="James Carrot" th:value="${myVariable}" />
            </form>
        </body>
    </html>

This is rendered to:

    <!DOCTYPE html>
    <html xmlns="http://www.w3.org/1999/xhtml" xmlns:th="http://www.thymeleaf.org">
        <body>
            <form>
                <input type="text" name="userName" value="James Carrot" th:value="myValue" />
            </form>
        </body>
    </html>

Instead of `<input type="text" name="userName" value="myValue" />`

**Comment by erdlet** [comment]
Thanks for reporting your issue. Can you please add a link to your example application, so we can have a look into it?

**Comment by thomas-mc-work** [comment]
Here you go: https://github.com/thomas-mc-work/krazo-tl-example

**Comment by erdlet** [comment]
Hi @thomas-mc-work ,

please try to change the file ending of your template to `.html`, as the Thymeleaf extension, or more precisely the `ThymeleafViewEngine`, just works for that: https://github.com/eclipse-ee4j/krazo/blob/91f72411c35daaea555219e4f9667e68a978a75b/ext/thymeleaf/src/main/java/org/eclipse/krazo/ext/thymeleaf/ThymeleafViewEngine.java#L61

After this the example should work :)

**Comment by thomas-mc-work** [comment]
Wonderful, thank you!

Another question is arising from your referenced code line: In my initial situation, I was able to resolve the explicit expression syntax ala `${myVariable}` (outside of the `th:…` attribute. This isn't possible now with the `html` file extension anymore. Why did that work before, when the method `supports` would return `false` when asked for another file extension?

**Comment by erdlet** [comment]
I guess the view was hit by the view engine for JSF, which supports
`.xhtml` files per default and is one of the default view engines specified
by the spec.

Thomas McWork <notifications@github.com> schrieb am Mi., 9. Sept. 2020,
11:42:
