### ISSUE TITLE
Question: Thymelaf template layouts

### ISSUE THREAD

**Issue by thomas-mc-work** [eclipse-ee4j/krazo#204]
There is a very convenient way to integrate every site into a global default layout, described in a blog post here:

https://blog.codeleak.pl/2013/11/thymeleaf-template-layouts-in-spring.html

Unfortunately this example is based on Spring, whereas I'm using Java EE. Can you give me a hint how to integrate that into my project? Or even better: Integrate that pattern into the Thymeleaf krazo extension out of the box. That'd be a very convenient addition for the users of that library.

**Comment by erdlet** [comment]
Hi,

I don't know this way the block post describes as I just use the existing layout dialect for my projects. But it seems, that this is similar to the way you can use to integrate the layout dialect, so maybe this is helpful:
https://www.erdlet.de/java/2019/11/09/krazo-thymeleaf-ext-engine-config.html

Thymeleaf and Jakarta EE is in general a  little bit complicated, as Thymeleaf is focused really much on the integration with Spring. So unfortunately I can't give you more detailed information about the interaction between Thymeleaf and Jakarta EE.

Regarding the idea of adding layout support to Krazo: I thought myself about something like this. But I came to a point where I thought that adding such features directly to Krazo is not a good idea, as there are too many ways for creating layouts in Thymeleaf and we should just provide the base mechanism for view rendering.

**Comment by erdlet** [comment]
As there was no more interaction on this issue, I'll close it for now. If there are further questions, please feel free to reopen.

**Comment by thomas-mc-work** [comment]
Thank you anyway!
