### ISSUE TITLE
1.1.0 release missing from Maven repositories?

### ISSUE THREAD

**Issue by jcputney** [eclipse-ee4j/krazo#214]
I see that the release was tagged, but I can't find it in any repositories. Do I need to add another repository to my pom.xml?

**Comment by erdlet** [comment]
@ivargrimstad can you please have a look into this?

**Comment by ivargrimstad** [comment]
It is currently staged. https://jakarta.oss.sonatype.org/content/groups/staging/org/eclipse/krazo/
We have to wait until the ballot for Jakarta MVC 1.1 completes before we publish it to central.

**Comment by erdlet** [comment]
Thanks for the information. I'll close this, as the question is answered and recognized by the author.
