### ISSUE TITLE
Reactivate the Handlebars extension

### ISSUE THREAD

**Issue by chkal** [eclipse-ee4j/krazo#231]
This extension is currently disabled, because the underlying template engine doesn't support the new `jakarta.*` package namespace yet. We have to:

 * Wait for a new version of the template engine and update our dependencies.
 * Reactivate the corresponding tests in our testsuite (currently disabled via `@Ignore`)

As a last resort we may also decide to remove the extension.

Please note that I assigned this issue to the `2.0.0` milestone. However, the issue should NOT be a blocker for the 2.0.0 release.

**Comment by erdlet** [comment]
It seems that Handlebars doesn't make any attempt to upgrade to the `jakarta` namespace. TBH, I think we should drop this extension too. The last commit was in October 2021 and since then there was no real activity.

**Comment by erdlet** [comment]
Migrated to [krazo-extensions](https://github.com/eclipse-ee4j/krazo-extensions). As the Krazo Extensions are not that tightly coupled to the Krazo versioning / release process, this extension was set to MVC 1.0 and Krazo 1.0.
