### ISSUE TITLE
Reactivate the Thymeleaf extension

### ISSUE THREAD

**Issue by chkal** [eclipse-ee4j/krazo#233]
This extension is currently disabled, because the underlying template engine doesn't support the new `jakarta.*` package namespace yet. We have to:

 * Wait for a new version of the template engine and update our dependencies.
 * Reactivate the corresponding tests in our testsuite (currently disabled via `@Ignore`)

As a last resort we may also decide to remove the extension.

Please note that I assigned this issue to the `2.0.0` milestone. However, the issue should NOT be a blocker for the 2.0.0 release.

**Comment by chkal** [comment]
I created a corresponding issue in the upstream project: thymeleaf/thymeleaf#811

**Comment by chkal** [comment]
I experimented with the Eclipse Transformer Maven Plugin and was successful:

Basically I added this to the upstream's Thymeleaf `pom.xml`:

```xml

      <!-- Create Jakarta EE 9 version of the artifact -->
      <plugin>
        <groupId>org.eclipse.transformer</groupId>
        <artifactId>org.eclipse.transformer.maven</artifactId>
        <version>0.2.0</version>
        <configuration>
          <classifier>jakarta</classifier>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>run</goal>
            </goals>
            <phase>package</phase>
          </execution>
        </executions>
      </plugin>
```

This creates an additional artifact having the classifier `jakarta` which is transformed to the jakarta namespace using Eclipse Transformer. I then updated our dependency on Thymeleaf to this:

```xml
<dependency>
    <groupId>org.thymeleaf</groupId>
    <artifactId>thymeleaf</artifactId>
    <version>3.0.13-SNAPSHOT</version>
    <classifier>jakarta</classifier>
</dependency>
```

After that `ThymeleafIT` is green again! :tada: 

I guess the simplest way to move forward is to provide a pull request for the upstream project. Although I'm not sure if they will accept it. Another approach would be to repackage Thymeleaf as part of our build. Any thoughts?

**Comment by erdlet** [comment]
I'm also not sure if they accept this, but maybe we should give this a try and open a PR :)

**Comment by chkal** [comment]
Done! https://github.com/thymeleaf/thymeleaf/pull/830

**Comment by gtudan** [comment]
I'd like to do both - they probably want to migrate manually, but meanwhile we could use the transformer to get this working. 

We'd have to think about publishing snapshots though - maybe we could ship a shaded version inside the extension?

**Comment by chkal** [comment]
I created a PR for adding the transformer maven plugin to their build. Let's see if they accept it.

I agree that it would be best to reactivate the extension ASAP. I also thought about shading in a modified version of Thymeleaf, but AFAIK that's not so easy with the existing Transformer plugin. So maybe we should just wait a few days to see if the upstream PR is accepted?

**Comment by chkal** [comment]
Unfortunately, they didn't accept my PR which created a separate artifact for Jakarta EE 9. But there seems to be some progress finally:

> Please note this is now in progress. First snapshots of 3.1.0-SNAPSHOT are already published, but note thorough testing is still ongoing.

See: https://github.com/thymeleaf/thymeleaf/issues/811#issuecomment-1005797229

**Comment by erdlet** [comment]
Maybe it's a good idea to integrate the Snapshot in our extension for testing?

**Comment by chkal** [comment]
I thought about this as well. But having snapshot dependencies in our master branch feels wrong. :laughing: And we will have to fix that before doing the next release. But anyway, it would be possible.

**Comment by chkal** [comment]
Good news! Thymeleaf 3.1.0.M1 is now available in Maven Central! :tada: 

https://github.com/thymeleaf/thymeleaf/issues/811#issuecomment-1015503065

**Comment by jelemux** [comment]
That's great! Can we integrate this or is it still too early?
I've been wanting to add support for [Thymeleaf Fragments](https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#fragments) (and Partial Page Rendering in general) so I'll need this.

**Comment by chkal** [comment]
I would be fine with using a milestone for now. Better than having no Thymleaf extension at all.

**Comment by erdlet** [comment]
> I've been wanting to add support for Thymeleaf Fragments (and Partial Page Rendering in general

Great idea, thanks for that in advance ;)

Regarding the general partial rendering: I think there was an issue in the spec where I investigated this a little bit. Maybe we can discuss this there as I think it makes less sense to implement a general solution for something not all template engines support in the same way. But maybe I'm wrong, so simply let us talk about it :)
