### ISSUE TITLE
Reactivate the Pebble extension

### ISSUE THREAD

**Issue by chkal** [eclipse-ee4j/krazo#234]
This extension is currently disabled, because the underlying template engine doesn't support the new `jakarta.*` package namespace yet. We have to:

 * Wait for a new version of the template engine and update our dependencies.
 * Reactivate the corresponding tests in our testsuite (currently disabled via `@Ignore`)

As a last resort we may also decide to remove the extension.

Please note that I assigned this issue to the `2.0.0` milestone. However, the issue should NOT be a blocker for the 2.0.0 release.

**Comment by chkal** [comment]
I created a corresponding issue in the upstream project: https://github.com/PebbleTemplates/pebble/issues/548

**Comment by chkal** [comment]
Upstream pull request: https://github.com/PebbleTemplates/pebble/pull/549

**Comment by chkal** [comment]
Upstream issue fixed. So we just have to wait for the next release, so we can use the new `Servlet5Loader`. Currently, the version in the `pom.xml` is set to `3.1.5-SNAPSHOT`. So `3.1.5` should work.

**Comment by erdlet** [comment]
`3.1.5` was released in february, so we can update and test the extension now.
