### ISSUE TITLE
Investigate GlassFish Integration

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/krazo#242]
We should start exploring what changes, if any, that must be done to Krazo in order to integrate it into GlassFish.
A good start would be to ask on the GlassFish mailing list for pointers to where to start.

**Comment by chkal** [comment]
I'll try to find some time early next week to reactivate our integration test profile which runs the tests against Glassfish with Krazo being installed as a Glassfish module. Let's see how many green tests we get. :-)

**Comment by ivargrimstad** [comment]
Great! And even greater if you could set it up as a Jenkins job to avoid the Travis issues we had last yer :)

**Comment by chkal** [comment]
See #243 for some more details about the current challenges.

**Comment by chkal** [comment]
The TCK now passes against Glassfish 6.1.0-M1 with Krazo installed as a module.

I also set up a corresponding Jenkins job which runs the TCK against 6.1.0-M1 and the 6.1.0-SNAPSHOT nighties:

![image](https://user-images.githubusercontent.com/159245/113505579-fde42e00-953f-11eb-9af7-8611e1522328.png)

Should we close this issue now? I guess we should wait with providing a pull request to integrate Krazo into Glassfish until 6.1.0 is out, correct?

**Comment by ivargrimstad** [comment]
Yes, I think we can close this issue and consider the investigation completed. And let's wait with the PR to GF until 6.1 is out.
