### ISSUE TITLE
Prepare PR to integrate into Glassfish

### ISSUE THREAD

**Issue by chkal** [eclipse-ee4j/krazo#245]
We should file a pull request to integrate Krazo into Glassfish after their 6.1.0 release.

**Comment by chkal** [comment]
See https://github.com/eclipse-ee4j/glassfish/pull/23479 :tada:

**Comment by erdlet** [comment]
Think we can close this as the PR was merged?

**Comment by ivargrimstad** [comment]
Yes, this one is done!
And GlassFish 6.2.0 has been released with Krazo included

https://download.eclipse.org/ee4j/glassfish/glassfish-6.2.0.zip
