### ISSUE TITLE
Upgrade JaCoCo to avoid exceptions during build

### ISSUE THREAD

**Issue by erdlet** [eclipse-ee4j/krazo#251]
We have this weird `IllegalClassFormatException: Error while instrumenting sun/util/resources/cldr/provider/CLDRLocaleDataMetaInfo` exception in all builds with JDK versions 16 and 17. After a short research, it seems that JaCoCo lacks support for JDK 16 and 17 or has only experimental support for it. After they release version `0.8.7`, I think we can upgrade JaCoCo and set the experimental flag for never JDK versions.

**Comment by chkal** [comment]
Thanks a lot for filing this issue. I guess in this case updating JaCoCo should fix the problem. So we should do so as soon as the new version is released.

**Comment by erdlet** [comment]
[JaCoCo 0.8.7](https://mvnrepository.com/artifact/org.jacoco/jacoco-maven-plugin/0.8.7) was released in May, so I think we can give it a try. I think I'll find time for it within the next days.
