### ISSUE TITLE
Extensions have inconsistent version numbers

### ISSUE THREAD

**Issue by gtudan** [eclipse-ee4j/krazo#254]
Something seems to have gone wrong with the 2.0.0-Release. Quiet a few extensions have not been released.

To name a few:

* jtwig
* thymeleaf
* jetbricks

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/419425/116000111-30d58b00-a5ef-11eb-8a2f-7e31b8c6ab4f.png">

They still have version 2.0.0-SNAPSHOT in the master branch.

**Comment by gtudan** [comment]
Okay, I get it now... Those extensions haven't yet switched to the jakarta.* namespace. 
Sadly, this makes it pretty much impossible to work on them until they either update, or we find a way use them nevertheless.

**Comment by chkal** [comment]
Yes, we disabled some modules as their corresponding upstream projects don't have versions which contain the namespace migration yet.

**Comment by erdlet** [comment]
Hi,

I reviewed the issues for these extensions yesterday and only Pebble is released with the Jakarta dependency at the moment (thanks to Christians PR). I have the feeling that JTwig and Jetbricks are unmaintained  and Thymeleaf is orienting itself on Spring, so changes on their side could take a while.

**Comment by erdlet** [comment]
Update: JTwig IS dead ;)

http://www.jtwig.org/

**Comment by chkal** [comment]
It would be great if we could find some way for Thymeleaf, as it is quite popular. Maybe some combination of shading and byte code transformation? 🧐

**Comment by chkal** [comment]
I wonder if integrating Eclipse Transformer with Maven Shade Plugin via the Resource Transformer API could do the trick... 🤔

**Comment by chkal** [comment]
Good news: https://github.com/eclipse-ee4j/krazo/issues/233#issuecomment-826547597

**Comment by erdlet** [comment]
Because Thymeleaf is on Jakarta namespace now and Jetbrick / JTwig removed I'll close this issue.
