### ISSUE TITLE
archetype: Set CSRF per default to implicit

### ISSUE THREAD

**Issue by erdlet** [eclipse-ee4j/krazo#255]
## Description

In https://github.com/eclipse-ee4j/mvc-api/issues/22 we wanted to set the CSRF default setting to `IMPLICIT` for security improvement. Unfortunately, we've overseen this issue for MVC 2.0.

As a workaround (and for easier migration later), the archetype shall create projects where CSRF is enabled by default. 

## Todos

- [x] Set CSRF to `IMPLICIT` in generated Jakarta REST Application

**Comment by chkal** [comment]
Big +1 for this.
