### ISSUE TITLE
Check all dependencies for updates and update them

### ISSUE THREAD

**Issue by erdlet** [eclipse-ee4j/krazo#260]
It's been a while since we checked all dependencies for updates and updated them. This should be done in the next time to ensure no to heavy version changes.

**Comment by chkal** [comment]
Good idea. Does anyone know more details about what changed regarding the CQ process? IIRC there were some major changes lately which simplify things a lot!?

**Comment by dmaidaniuk** [comment]
Hi @chkal  and @erdlet . I prepared PR with the needed changes for this ticket. Also, I added `versions-maven-plugin` plugin for automation of the work in the future.

**Comment by erdlet** [comment]
Hi @dmaidaniuk,

thanks a lot! I already commented on the PR :) Just need to check where we have to do some EF paperwork to get the PR merged asap.

**Comment by erdlet** [comment]
Resolved with #286
