### ISSUE TITLE
Remove Jsr223 extensions as Nashorn engine is removed since JDK 15

### ISSUE THREAD

**Issue by erdlet** [eclipse-ee4j/krazo#277]
The Nashorn engine was deprecated with JDK 11 and removed in JDK 15. I don't think we should provide further support for this. Any thoughts @eclipse-ee4j/ee4j-krazo-committers?

**Comment by gtudan** [comment]
+1 for removing it.

Using it as view engine probably isn’t something that was done very often. 
If someone did and wants to keep using it, it’s just a single class that can easily be copied.

**Comment by chkal** [comment]
+1 for removing it as well.

**Comment by erdlet** [comment]
Thanks for your thoughts. After I got the same feedback on the mailing list I'll remove the extension within the next days.
