### ISSUE TITLE
@MVCBinding on bean property not working on Tomee 8.0.10

### ISSUE THREAD

**Issue by AlessioBandoni** [eclipse-ee4j/krazo#294]
Hi, I was trying this new MVC Api, but I ran in some problems regarding validation of beans
This is the code of the action 
```
 @POST
    public String post(@BeanParam @Valid DefineEventForm form) {

        return "redirect:/define-event";
    }
```

this is the bean class

```
@RequestScoped
public class DefineEventForm  {

    @FormParam("date")
    @MvcBinding
    private String date;

    @FormParam("type")
    @MvcBinding
    private String type;

    @FormParam("category")
    @MvcBinding
    private String category;

    @FormParam("tags")
    @MvcBinding
    private String tags;

    @FormParam("text")
    @Max(10)
    @MvcBinding
    private Integer text;
```

After some digging I found out that the invocation of the method is intercepted by a org.apache.bval.cdi.BValInterceptor which triggers a constraint violation exception which blocks the request processings and causes the server to return a 400 response.

**Comment by erdlet** [comment]
Hi @AlessioBandoni,

thanks for trying Krazo, Jakarta MVC and filing this issue.

From my point of view the method looks fine. Can you provide a link to this example project so we can debug this?

Also this problem can be one of the multiple issue we had with CXF and Apache's Bean Validation implementation. This is the reason we dropped support for CXF. If you want to use a stable implementation, you should try `krazo-jersey` on Payara / Glassfish or `krazo-resteasy` on WildFly.

**Comment by AlessioBandoni** [comment]
Hi, thank you for the reply, now I understand why I was experiencing bugs. The test project is located at this repository:
https://github.com/AlessioBandoni/test-krazo

Unfortunately I'm accustomed to Tomee or Tomcat, testing on other application servers will require some time since I don't use any of the mentioned. I tried using rest easy on Tomee 8.0.10 but I had a strange error about an UrlProvider or something not being a SERVER provider. I can't recall exactly, but I guess it has nothing to do with Krazo.

**Comment by AlessioBandoni** [comment]
I managed to test the project with krazo 1.0 for WildFly 26.1 Java EE 8 and now the binding and validation are working as expected.

I'm surprised, Tomee is not some niche application server, do you plan to resume support for CXF in the future or working with this library is simply too difficult?

**Comment by erdlet** [comment]
> I managed to test the project with krazo 1.0 with WildFly 26.1 Java EE 8 and now the binding and validation are working as expected.

Happy to hear this :)

> I'm surprised, Tomee is not some niche application server, do you plan to resume support for CXF in the future or working with this library is simply too difficult?

So this is my personal opinion: I spent many hours on debugging CXF and Bean Validation on TomEE and the old OpenLiberty versions and I say: yes, it is too difficult. So if there is no CXF dev helping us, I'm afraid we won't add this integration again. In general, I'd prefer an own implementation provided by Apache, so it is ensured it works in their ecosystem.

**Comment by AlessioBandoni** [comment]
> > I managed to test the project with krazo 1.0 with WildFly 26.1 Java EE 8 and now the binding and validation are working as expected.
> 
> Happy to hear this :)
> 
> > I'm surprised, Tomee is not some niche application server, do you plan to resume support for CXF in the future or working with this library is simply too difficult?
> 
> So this is my personal opinion: I spent many hours on debugging CXF and Bean Validation on TomEE and the old OpenLiberty versions and I say: yes, it is too difficult. So if there is no CXF dev helping us, I'm afraid we won't add this integration again. In general, I'd prefer an own implementation provided by Apache, so it is ensured it works in their ecosystem.

I understand, thanks for the explanation.
