### ISSUE TITLE
MvcEventsTest fails in TCK on WildFly 26.1.1

### ISSUE THREAD

**Issue by erdlet** [eclipse-ee4j/krazo#297]
When I run the TCK against WildFly 26.1.1 on OpenJDK 17, the following error occurs:

```
java.lang.NullPointerException: Cannot invoke "jakarta.servlet.http.HttpServletRequest.getParameter(String)" because "this.request" is null
	at deployment.fc56bf10-6a81-4997-9bd7-c10063620052.war//jakarta.mvc.tck.tests.events.TraceManager.logInternal(TraceManager.java:61)
	at deployment.fc56bf10-6a81-4997-9bd7-c10063620052.war//jakarta.mvc.tck.tests.events.TraceManager.eventObserved(TraceManager.java:43)
	at deployment.fc56bf10-6a81-4997-9bd7-c10063620052.war//jakarta.mvc.tck.tests.events.MvcEventObserver.observeBeforeControllerEvent(MvcEventObserver.java:34)
```

**Comment by chkal** [comment]
As mentioned on Slack, I guess we need to extend the build matrix on Jenkins to catch these things earlier!?

**Comment by erdlet** [comment]
+1. Think we need to optimize the Jenkins jobs in general. Maybe by using Pipelines, where the maintenance effort is less than with the currently used classic builds.

**Comment by chkal** [comment]
I'm not super familiar with Jenkins pipelines, TBH. My impression is that multi-config builds work quite good at the moment. I'm currently trying to get the latest Wildfly releases into our jobs..

**Comment by chkal** [comment]
I updated our Jenkins configuration by replacing older Wildfly release with the newer ones.

I can confirm that the TCK runs fine with `25.0.1` and `26.0.1` but fails with `26.1.1`.

**Comment by erdlet** [comment]
Seems like everything is fine now. The TCK is green again. I'll close this issue. Thanks for your help @chkal
