### ISSUE TITLE
A few TCK tests fail on Glassfish 7.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by chkal** [eclipse-ee4j/krazo#299]
Not sure if this is already too late, but we should try to fix these before 7.0.0 is released:

![image](https://user-images.githubusercontent.com/159245/170865649-bd8141e1-70b6-4afb-a7ea-10af21b11293.png)

See: https://ci.eclipse.org/krazo/job/tck-glassfish/jdk=openjdk-jdk17-latest,version=7.0.0-SNAPSHOT-nightly/21/console

**Comment by erdlet** [comment]
Seems like CDI and Validation changes some behavior. I'll investigate this asap. Same tests fail in WF 26.1.1 too.
