### ISSUE TITLE
Create CQs for third-party dependencies

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/krazo#30]
## Krazo Code
  * [x] [Java EE Web API](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18560)
  * [x] [MVC API](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18561)
  * [x] [Servlet API 4.0](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18587)
  * [x] [CDI 2.0](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18588)
  * [x] [Bean Validation 2.0](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18589)
  * [x] [Jersey 2.27](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18590)
  * [x] [JUnit 4.12](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18591)
  * [x] [Easymock 3.3.1](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18592)
  * [x] [Weld SE 2.4.8.Final](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18593)
  * [x] [Hibernate Validator 5.4.1.Final](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18594)
  * [x] [EL Impl 3.0.1](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18595)

## Krazo Jersey/RESTEasy/CXF
  * [x] [RESTEasy](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18596)
  * [x] [CXF](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18597)

## Krazo Extensions
  * [x] [AsciidoctorJ 1.5.7](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18834)
  * [x] [Freemarker 2.3.28](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18835)
  * [ ] [Groovy Templates 2.5.3](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18836)
  * [x] [Handlebars.java 4.1.0](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18837)
  * [x] [Jade4J 1.2.7](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18838)
  * [x] [Jetbrick 2.1.6](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18839)
  * [x] [Antlr 4.7.1](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18840)
  * [x] [Jtwig Web 5.87.0](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18841)
  * [x] [Mustache Java Compiler 0.9.5](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18842)
  * [x] [Pebble 2.4.0](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18843)
  * [x] [StringTemplate 4.0.8](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18844)
  * [x] [Thymeleaf 3.0.10](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18845)
  * [x] [Velocity Tools 3.0](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18846)

## Test-only / build-only dependencies
  * [x] [Umbrella CQ for build/test dependencies](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18898)

Please only mark the task as CHECKED if the CQ has been approved.

**Comment by chkal** [comment]
I just filed 13 new CQs for the compile-scoped dependencies of the extension modules. Let's see if we have any license issues there.

**Comment by chkal** [comment]
I just filed the last CQ for Krazo. This CQ is an umbrella CQ for our test and build dependencies:

https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18898

**Comment by chkal** [comment]
Good news. Most of the CQs are resolved. Only 2 of the 28 are still pending:

  * [Groovy](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18836)
  * [Krazo itself](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18559)

We are getting closer to the finish line. :-)

**Comment by chkal** [comment]
I close this issue now. We removed our dependency on Groovy and Krazo itself isn't really a 3rd party dependency.
