### ISSUE TITLE
Maintain dependency versions in parent pom's

### ISSUE THREAD

**Issue by erdlet** [eclipse-ee4j/krazo#310]
To have only one point for maintaining our dependencies' versions, they shall be set via `dependencyManagement` inside the `krazo-parent` or `ext-parent` pom.

As we may separated the `ext` module in the future, having those versions maintained in the common Krazo parent wouldn't make sense.

**Comment by chkal** [comment]
I agree that having dependency versions in the parent pom is a good idea. Currently, we do this only for a few important dependencies, like the spec version for example.

**Comment by erdlet** [comment]
Closed. Was done together with the update to Jakarta EE 10
