### ISSUE TITLE
Add `remote` and `managed` testsuite profile

### ISSUE THREAD

**Issue by erdlet** [eclipse-ee4j/krazo#313]
To be able to run the testsuite more easily on local and CI environments, it makes sense to create a `remote` and `managed` profile with the corresponding Arquillian adapters. This way, someone can run those tests without caring about downloading the server, but is able to debug it using the `remote` profile.

**Comment by chkal** [comment]
+1

I personally prefer the `remote` adapters, but supporting both type is definitely valuable.

**Comment by erdlet** [comment]
Managed profile for WildFly added.

**Comment by erdlet** [comment]
Think we have all relevant profiles now.
