### ISSUE TITLE
Define extensions to keep and discuss extraction into own repository

### ISSUE THREAD

**Issue by erdlet** [eclipse-ee4j/krazo#319]
This issue shall be a base for defining extensions we want to keep maintained by the Krazo team. Also it has to be discussed, if some or all extensions will be moved into a separate repository to reduce maintenance effort in the Krazo repository and to focus on the development of Krazo Core.

To get a quick overview over our extensions and the status of the underlaying template engine, I'll add a list here so we can discuss about them.

@eclipse-ee4j/ee4j-krazo-committers please comment here if there is an extension that must be kept or, on the other hand, can simply be deleted in your opinion

**Edit**: These are all engines supported by an extension with some additional info which may help to decide how to proceed.

| Extension | Template engine | latest version | ext. version | jakarta namespace? | comments | maintainer |
|---------------|------------------------|-------------------|-----------------|----------------------------|----------------|----------------|
| asciidoc | [asciidoctorj](https://mvnrepository.com/artifact/org.asciidoctor/asciidoctorj) | 2.5.4 | 2.5.2 | yes | --- | --- |
| freemarker | [freemarker](https://mvnrepository.com/artifact/org.freemarker/freemarker/2.3.31) | 2.3.31 | 2.3.31 | yes | --- | --- |
| jade | [jade4j](https://mvnrepository.com/artifact/de.neuland-bfi/jade4j/1.3.2) | 1.3.2 | 1.3.2 | yes | looks abandoned and has vulnerabilities | --- |
|mustache | [mustache.java](https://mvnrepository.com/artifact/com.github.spullara.mustache.java/compiler/0.9.10) | 0.9.10 | 0.9.10 | yes | --- | --- |
| pebble | [pebble](https://mvnrepository.com/artifact/io.pebbletemplates/pebble) | 3.1.5 | 3.1.5 | yes | --- | --- |
| stringtemplate | [ST4](https://mvnrepository.com/artifact/org.antlr/ST4) | 4.3.1 | 4.3.3 | yes | --- | --- |
| thymeleaf | [Thymeleaf](https://mvnrepository.com/artifact/org.thymeleaf/thymeleaf) | 3.1.0.M1 | 3.1.0.M2 | yes | --- | @erdlet |
| velocity | [velocity](https://mvnrepository.com/artifact/org.apache.velocity/velocity-engine-core) | 2.3 | 2.3 | yes | --- | --- |
| handlebars | [handlebars](https://mvnrepository.com/artifact/com.github.jknack/handlebars) | 4.3.0 | 4.2.0 | no | looks not regularly updated | @jcputney |
| jetbrick | [jetbrick](https://mvnrepository.com/artifact/com.github.subchen/jetbrick-template) | 2.1.10 | 2.1.10 | no | looks abandoned.  | --- |
| jinjava | [jinjava](https://mvnrepository.com/artifact/com.hubspot.jinjava/jinjava/2.6.0) | 2.6.0 | 2.6.0 | no | [PR for jakarta namespace](https://github.com/HubSpot/jinjava/pull/810) open but needs attention | --- |

**Comment by jcputney** [comment]
We use the Handlebars extension, so if you need a maintainer, I might be able to take that on.

**Comment by erdlet** [comment]
Thanks for your feedback @jcputney :) Would be great  if you take care of this extension.

**Comment by erdlet** [comment]
I added a table with information about all extensions and the used template engines.

**Comment by erdlet** [comment]
Jade4J is now [pug4j](https://github.com/neuland/pug4j). So I'll remove the Jade4J extension and, if someone wants to use it, an new extension for pug4j needs to be created.

**Comment by erdlet** [comment]
The extensions are migrated to [krazo-extensions](https://github.com/eclipse-ee4j/krazo-extensions). This issue will be closed after #328 is merged.

**Comment by ivargrimstad** [comment]
I think we should consider keeping asciidoc (depending on the amount of maintenance required). Not that it is necessarily much used right now, but it provides a migration path if someone wants to move e.g. gh-pages with asciidoc or similar down the road

**Comment by erdlet** [comment]
> I think we should consider keeping asciidoc (depending on the amount of maintenance required). Not that it is necessarily much used right now, but it provides a migration path if someone wants to move e.g. gh-pages with asciidoc or similar down the road

I migrated all plugins except Jade and Jetbricks :)
