### ISSUE TITLE
Update all dependencies to final versions

### ISSUE THREAD

**Issue by erdlet** [eclipse-ee4j/krazo#339]
At the moment we use a few provided dependencies on milestone versions. They shall be replaced by their final implementations.

**Comment by dmaidaniuk** [comment]
@erdlet I updated all dependencies where possible.

**Comment by erdlet** [comment]
Thanks for the updates. I'll keep the issue open until every dependency has a final version.

**Comment by erdlet** [comment]
Closing this now since this is an ongoing task
