### ISSUE TITLE
Make managed wildfly version in tck run configurable

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/krazo#347]
It is now hardcoded to 27.0.0.Alpha3. Should be configurable by environment

**Comment by erdlet** [comment]
Hi @ivargrimstad,

I checked the build an you can set the WildFly version by adding `-Dwildfly.version`. The WildFly TCK job is updated to test against `27.0.0.Alpha5` and `27.0.0.Beta1` as an example.
