### ISSUE TITLE
Broken data binding on Wildfly

### ISSUE THREAD

**Issue by chkal** [eclipse-ee4j/krazo#53]
It looks like the parameter binding is currently broken Wildfly. The TCK now also checks all the assertions for the data binding, so we are getting about 11 TCK failures on Wildfly.

Let me try to explain what I know so far:

Krazo basically needs to perform the data binding AND validation itself. This is required so we can put all the details about failures into `BindingResult` and then invoke the controller even in case of failures instead of simply sending a 400 Bad request response.

To do this, we need to disable the native Bean Validation integration with JAX-RS. We are currently doing this with a "dirty trick". Hibernate Validator uses a CDI extension to observe `ProcessAnnotatedType` events and then adds an interceptor binding annotation to corresponding resources. This allows Hibernate Validator to execute the actual validation via a CDI interceptor.

To disable this, we also register a CDI extension which observers `ProcessAnnotatedType` and simply remove the interceptor binding annotation which was added by Hibernate Validator for controller classes. Yes, I know, this is a bit sneaky, but it worked back then. :-)

For some reason (which I don't fully understand yet), this doesn't work in recent Wildfly versions anymore. Our CDI extension is randomly executed either before or after the Hibernate Validator extension. If we are executed after it, everything works, if we are executed before, the binding stops to work correctly, because Hibernate Validator does the validation and responds with a 400 status code.

I already created [WELD-2568](https://issues.jboss.org/browse/WELD-2568), as I think this behavior is not correct. I'm hoping to get more feedback on this soon.

**Comment by chkal** [comment]
More good news. The upstream issue has been fixed and the fix will be part of Weld 3.1.1.Final.

**Comment by chkal** [comment]
Some updates for this. I created the new `tck-wildfly16-patched` Travis profile, which runs the TCK against Wildfly 16 including a backport of [WELD-2568](https://issues.jboss.org/browse/WELD-2568).

Unfortunately most of the data binding tests still don't pass. I had another deeper look at the issue and found out, that RESTEasy doesn't apply custom `ParamConverter` for primitive types. Therefore, MVC data binding doesn't work for all primitive data types (boolean, double, int, long, etc.). I created [RESTEASY-2222](https://issues.jboss.org/browse/RESTEASY-2222) to track this. I hope that the RESTEasy teams agrees that not supporting custom converters for primitive types is a violation of the spec. Feel free to vote or comment on this issue if you like.

**Comment by chkal** [comment]
Still no response from the RESTEasy team. :disappointed: 

But I just created eclipse-ee4j/jaxrs-api#762 to add a clarification to the JAX-RS API docs regarding this issue.

**Comment by gtudan** [comment]
@chlal the issue you mentioned has been resolved in RestEasy 3.7.0. I guess we can close this since WF17 ships this version and the TCK passes, right?

**Comment by chkal** [comment]
Oh, yeah, thanks. Forgot to close this one!
