### ISSUE TITLE
Krazo stopped working with OpenLiberty 19

### ISSUE THREAD

**Issue by gtudan** [eclipse-ee4j/krazo#63]
It seems Krazo stopped working in OpenLiberty 19 (I'm testing on 19.0.0.3). It will trigger an exception on deployment

```
java.lang.IllegalArgumentException: The controller it.mulders.junk.mvc.presentation.HelloController is not a managed CDI bean. Maybe the controller class is missing a scope annotation (e.g. @RequestScoped).
[INFO] 	at org.eclipse.krazo.servlet.KrazoServletContextListener.failIfNoCdiBean(KrazoServletContextListener.java:78)
[INFO] 	at org.eclipse.krazo.servlet.KrazoServletContextListener.contextInitialized(KrazoServletContextListener.java:62)
[INFO] 	at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated(WebApp.java:2377)
[INFO] 	at [internal classes]
[INFO]
[INFO] [WARNUNG ] The ServletContext wasn't injected into the JAX-RS Feature class
```

The same app works fine on OpenLiberty 18.

**Comment by chkal** [comment]
Could you try to set `bean-discovery-mode="all"` in the `beans.xml` file? IIRC the default mode is `annotated` which means that you will need some kind of CDI annotation on the controller to tell CDI that it should pick up the class.

**Comment by gtudan** [comment]
That worked. I wonder why they changed that 🤔 
I always used to drop an empty beans.xml into my project. Thanks for the hint!

**Comment by chkal** [comment]
Maybe we could improve the error message a bit?

**Comment by gtudan** [comment]
I'd like that. To be honest I didn't quiet get where the exception was coming from. RestEasy behaves different, so a pointer to beans.xml would be nice. 

I created a PR for this.
