### ISSUE TITLE
Allow building with OpenJDK > 8

### ISSUE THREAD

**Issue by gtudan** [eclipse-ee4j/krazo#97]
I would like to be able to compile the project with more recent JDK-Versions. The Oracle JDK8 is no longer supported, so we shouldn‘t require developers to stick with it.

The build can be kept backwards-compatible with earlier Java versions by using the -release flag.

We already did this for the the MVC-Spec (see its pom-File).

**Comment by chkal** [comment]
Big +1 for this one!

**Comment by mthmulders** [comment]
Good one! Maybe we could use a [Build Matrix](https://docs.travis-ci.com/user/build-matrix/) to build on multiple Java versions at the same time. What versions do we want to build on? I'd guess at this point 8, 11 and 13 (with 11 being the latest LTS and 13 being the latest regular release)...

**Comment by chkal** [comment]
Maybe we should change `oraclejdk8` to `openjdk8` in a first step?

Basically I like the idea of running the build with multiple JDK version, but the build matrix is already a bit complex, as we run the integration tests and the TCK against multiple container profiles.

**Comment by mthmulders** [comment]
Switching to OpenJDK would be a good (and simple) first step. I'll provide a PR for that, it's a quick win.

I think the next thing we could do is start _building_ Krazo with multiple Java versions. The last step would be to run the TCK against multiple containers running multiple versions of Java. That last part is indeed going to be a complex one. I just don't know yet if we could separate the phases of the build like that...
